name: Feature Request 🚀
description: Create a new feature request
title: '[New Feature]: '
labels: ['feature request']
body:
  - type: markdown
    attributes:
      value: |
        If you have any new ideas for features or improvements, please note all relevant requirements for your feature.
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What are the requirements for your feature?
      placeholder: Describe your feature here.
      value: 'I need a new feature to perform X.'
    validations:
      required: true
  - type: textarea
    id: considerations
    attributes:
      label: Considerations
      description: What are things to consider for this feature?
      placeholder: Describe considerations for this feature.
      value: 'We may want to have this feature do X in a certain way.'
    validations:
      required: true
  - type: dropdown
    id: area-of-focus
    attributes:
      label: Area of Focus
      description: What are the area of focus that this feature encompasses?
      multiple: true
      options:
        - Frontend
        - Backend
        - DevOps
        - Infrastructure
    validations:
      required: true
