name: Feedback 💬
description: Create a feedback post
title: '[Feedback]: '
labels: ['feedback']
assignees:
  - jhanke00
  - thychamp
  - srikanthbandaru
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a feedback form!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: feedback
    attributes:
      label: What feedback do you have about this format?
      description: Did you have any comments, questions, or concerns with the format?
      placeholder: Tell us your experience.
      value: 'I really enjoyed this format!'
    validations:
      required: true
